### ISSUE TITLE
spec-tools.parse/parse-form 'spec-tools.core/merge throws when merging with symbol

### ISSUE THREAD

**Issue by slipset** [metosin/spec-tools#211] opened 2020-02-03 10:48 UTC
```clojure
(s/def ::bar string?)
(s/def ::qix string?)
(s/def ::foo (s/keys :req-un [::bar]))
(s/def ::baz (s/keys :req-un [::qix]))
(spec-tools/merge ::foo ::bar)
;; works fine
(def bar ::bar)
(spec-tools/merge ::foo bar)
;; throws
```

**Comment by slipset** [comment] 2020-03-11 12:07
```clojure
(defmethod parse-form 'spec-tools.core/merge [_ form]
  (let [type-priority #({:map        1
                         :multi-spec 0} (:type %) 0)]

    (apply impl/deep-merge (->> (rest form)
                                (map parse-spec)
                                (sort-by type-priority)))))
```
makes the problem go away, but not sure if it's a correct fix

**Comment by wandersoncferreira** [comment] 2020-04-05 02:02
Hi, seems like the problem went away with the current state of master. There were a PR related to this symbol problem that might have fixed this as well. I can't reproduce the failure example now.

**Comment by ikitommi** [comment] 2020-04-13 11:03
Fixed in master

**Closed by ikitommi** 2020-04-13 11:03 UTC
Labels: bug, help wanted
